# Generated by Django 5.0.6 on 2024-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalmanIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='salmanid/photos/')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('qr_code', models.ImageField(upload_to='salmanid/qrcodes/')),
            ],
        ),
    ]
