# Generated by Django 5.0.6 on 2024-10-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salmanId', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='blood_group',
            new_name='Blood_group',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='designation',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='dob',
            new_name='Dob',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='emp_id',
            new_name='Emp_id',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='mobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='photo',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='salmanidcard',
            old_name='qr_code',
            new_name='Qr_code',
        ),
    ]
