# Generated by Django 5.0.6 on 2024-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PorfaidIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('porfa_id', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='porfaid/photos/')),
                ('dob', models.DateField()),
                ('patient_address', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('qr_code', models.ImageField(upload_to='porfaid/qrcodes/')),
                ('ration_card', models.CharField(choices=[('APL', 'APL'), ('BPL', 'BPL')], max_length=3)),
                ('treatment_type', models.CharField(choices=[('Dialysis', 'Dialysis'), ('Transplant', 'Transplant')], max_length=10)),
            ],
        ),
    ]
