# Generated by Django 5.0.6 on 2024-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfaId', '0002_porfaidcard_delete_porfaididcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfaidcard',
            name='last_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='porfaidcard',
            name='treatment_type',
            field=models.CharField(choices=[('D', 'Dialysis'), ('T', 'Transplant')], max_length=10),
        ),
    ]
